[Refactor] 이펙트 매니저 리펙토링.
KIA-PROGRAMMING-38/Moonlighter pull request #93
Opened 2023-07-06 09:36 UTC by password-kim

# PR을 하기 전 체크사항
PR 전에 아래의 내용을 수행했는지 하나씩 체크해봅시다.

- [x] 임시로 작성한 코드는 모두 제거했나요?
- [x] 주석은 충분히 작성했나요?
- [x] 실행했을 때, 오류는 없나요?
- [x] 커밋 메시지는 [가이드](https://docs.google.com/document/d/1bDgWctGEprMvLzV5OpuZV1-BCnrhVVJ19cd8D9tFArU/edit#heading=h.jgj6vfjils4q)에 맞춰 작성됐나요?

# 변경된 기능

- 이펙트 매니저 리펙토링.

# 제안 사항

- EffectManager에서 PlayEffect메서드로 다양한 이펙트 재생에 대응할 수 있도록 수정.
> 이펙트 종류에 따라 그에 맞춰 메서드를 추가하면 이펙트 매니저가 비대해지기 때문.
- Effect 클래스를 EffectController로 바꿈.
> 클래스 이름이 모호해서.
- 이펙트 효과를 EffectController 클래스에 있는 메서드로 애니메이션 이벤트를 활용해 이펙트 효과 적용.
> 기존 이펙트 매니저에서 이펙트 효과까지 적용해주면 이펙트 매니저가 해야할 일이 많아지기 때문.
> 모듈화목적.

# 스크린샷

https://github.com/KIA-PROGRAMMING-38/Moonlighter/assets/72890183/782b1a2b-3fc9-44c9-9cd2-6f2ae5fdcd80

# (선택)관련 이슈

- [x] #92 

---

2023-07-06 10:42 UTC, ChoiSeonMun requested changes

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Managers/DataManager.cs
> +    public Dictionary<int, EffectAnimatorControllerData> EffectAnimatorControllerDataTable = new Dictionary<int, EffectAnimatorControllerData>();
EffectDataTable

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Managers/ResourceManager.cs
> +    private Dictionary<string, AnimatorController> _effects = new Dictionary<string, AnimatorController>();
EffectManager과 관리해야 함

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Managers/ResourceManager.cs
> +    private Material LoadMaterial(string path)
```suggestion
public static T Load<T>(this Dictionary<string, T> _dict, string path) where T : UnityEngine.Object
	{
		if (false == _dict.ContainsKey(path))
		{
			T resource = Resources.Load<T>(path);
			_dict.Add(path, resource);
		}

		return _dict[path];
	}
```

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/BodyEffectController.cs
> +    private Vector3 _footPosition;
삭제

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/BodyEffectController.cs
> +    private Vector3 _footPositionOffset;
삭제

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/BodyEffectController.cs
> +    private Transform _moveEffectPos;
_moveEffectTransform

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/BodyEffectController.cs
> +    private void SetFootPositionOffset()
```suggestion
private Vector3 GetFootEffectSpawnPosition()
{
    Vector3 offset = GetOffset(dir);
    
    return _moveEffectPos.position + offset;

    static Vector3 GetOffset(FacingDirection dir)
    {
        switch (dir)
        {
            case FacingDirection.Down:
                return new Vector3(Random.Range(-0.04f, 0.04f), 0.1f);
            case FacingDireciotn.Up:
                return new Vector3(Random.Range(-0.04f, 0.04f), 0f);
            case FacingDirection.Left:
                return new Vector3(0f, Random.Range(-0.02f, 0.04f));
            case FacingDirection.Right:
                return new Vector3(0f, Random.Range(-0.02f, 0.04f));
            default:
                throw new NotImplementedException();
        }
    }
}
```

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerIdleState.cs
> +        _player.SetFacingDirection();
삭제

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
> +        _player.SetFacingDirection();
삭제

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
> +        _defaultRollSpeed = Managers.Data.CharacterStatDataTable[(int)CharacterStatId.Player].RollSpeed;
PlayerController에 있음.

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
>      private void SetRollVelocity(AnimatorStateInfo stateInfo)
다시 작성

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
>          _rollVelocityMultiplier = EaseFunc.EaseOutCubic(_rollVelocityMultiplier, _player.Stat.RollSpeed, Time.deltaTime / stateInfo.normalizedTime);
DoTween

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
>          if (_animEventHandler.IsAnimationFinsih)
??

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/Animations/Player/Player_Roll_Down.anim
이름에 _ 왜?

2023-07-06 10:42 UTC, ChoiSeonMun commented on Moonlighter/Assets/Data/EffectAnimatorControllerDataTable.csv
경로 규칙이 있다면 Path열 불필요

2023-07-07 03:33 UTC, ChoiSeonMun requested changes
DataManager 개선

2023-07-07 03:33 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Managers/DataManager.cs
>  public class DataManager
```suggestion
class TestData
{
    public int Id { get; set; }
    public string Name { get; set; }
}

class DataManager
{
    private Dictionary<int, TestData> _dict;

    public void Init()
    {
        _dict = LoadCsv<TestData>("Data/TestData").ToDictionary(data => data.Id);
    }
    
    public IEnumerable<T> LoadCsv<T>(string path)
    {
        using (var reader = new StreamReader(path))
        {
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                return csv.GetRecords<T>();
            }
        }
    }
}
```

2023-07-07 03:33 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Managers/DataManager.cs
>  public class DataManager
Parse보다 LINQ를 쓰면 훨씬 간단함.
자세한 것은 [여기](https://learn.microsoft.com/ko-kr/dotnet/api/system.linq.enumerable.todictionary?view=net-7.0) 참조

2023-07-07 06:03 UTC, password-kim commented on Moonlighter/Assets/1_Scripts/Character/Character.cs
> +    protected CharacterStatData stat = new CharacterStatData();
해결.

2023-07-10 05:37 UTC, ChoiSeonMun requested changes

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/PlayerCharacter.cs
> +        int dirX = Mathf.RoundToInt(Anim.GetFloat(PlayerAnimParameters.MoveX));
```suggestion
int nextDirX = 1 + Mathf.RoundToInt(Anim.GetFloat(PlayerAnimParameters.MoveX));
```

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/PlayerCharacter.cs
> +        int dirY = Mathf.RoundToInt(Anim.GetFloat(PlayerAnimParameters.MoveY));
```suggestion
int nextDirY = Mathf.RoundToInt(Anim.GetFloat(PlayerAnimParameters.MoveY);
```

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/PlayerCharacter.cs
> +        PlayerFacingDirection = _facingDirections[++dirY, ++dirX];
```suggestion
        PlayerFacingDirection = _facingDirections[nextDirX, nextDirY];
```

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
> +        if (stateInfo.normalizedTime >= 1)
```suggestion

if (IsStateEnd(stateInfo))

static bool IsStateEnd(AnimatorStateInfo stateInfo) => stateInfo.normalizedTime >= 1;
```

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
>              if(_input.MoveInput != Vector2.zero)
```suggestion
_player.Anim.SetBool(PlayerAnimParameters.Roll, false);

if (_input.MoveInput == Vector2.Zero)
{
  _player.Anim.SetBool(PlayerAnimParameters.Idle, true);
}
else
{
  _player.Anim.SetBool(PlayerAnimParameters.Move, true);
}
```

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Utils/AnimationNameToHash.cs
한 파일에 해시값이 전부 정의가 되어있었으면 좋겠음. 관리가 너무 힘듦.

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/6_Scenes/TestScene.unity
다음 커밋부터는 이런 불필요한 것은 빠졌으면 좋겠음.

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
> +        if (_input.MoveInput == Vector2.zero)
이거 체크하는 코드가 많던데, input에 프로퍼티로 넣으면 좋을 듯.

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
> +    private Vector3 _rollDir;
```suggestion

```

필드로 들고 있을 이유가 전혀 없음. SetRollVelocity() 안에서 전부 만들면 됨.

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
> +            _rollDir = _directions[(int)_player.PlayerFacingDirection] * _rollDirModifier;
```suggestion
private void DoRoll(float duration)
{
    Vector3 direction = GetDirection();
    direction.Normalize();
    direction *= _rollDirModifier;

    _player.Rigid.DOMove((Vector2)direction, duration).SetEase(Ease.OutSine);
}

private Vector2 GetDirection()
{
    if (_input.IsMoving)
    {
        int newX = _player.Anim.GetFloat(PlayerAnimParameters.MoveX);
        int newY = _player.Anim.GetFloat(PlayerAnimParameters.MoveY);
        return new Vector2(newX, newY);
    }
    else
    {
        return _player.PlayerFacingDirection.ToVec2();
    }
}

static class Extensions
{
    private static Vector2[] _directions = { Vector2.up, Vector2.down, Vector2.left, Vector2.right };
    public static Vector2 ToVec2(this FacingDirection fd)
    {
        return _directions[(int)fd];
    }
}
```

2023-07-10 05:37 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerRollState.cs
> +    private Vector3[] _directions =
삭제

2023-07-10 09:03 UTC, ChoiSeonMun requested changes

2023-07-10 09:03 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Player/States/PlayerIdleState.cs
> +            ChangeToNextState(PlayerAnimParameters.Roll);
```suggestion
public void ChangeNextState(int current, int next)
{
  ExitCurrentState(current);
  EnterNextState(next);
}
```

2023-07-10 09:03 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Managers/EffectManager.cs
> +        anim.runtimeAnimatorController = Managers.Resource.Load<AnimatorController>(_effectTable, $"{EFFECT_PATH}{effectAnimController}");
```suggestion
        anim.runtimeAnimatorController = Managers.Resource.Load<AnimatorController>(_effectTable, Path.Combine(EFFECT_PATH, effectAnimController));
```

2023-07-11 00:46 UTC, ChoiSeonMun approved these changes

2023-07-11 00:46 UTC, ChoiSeonMun commented on Moonlighter/Assets/1_Scripts/Effect/EffectState/EffectState.cs
> +        if (IsStateEnd(stateInfo))
폴링 대신에 End 상태를 만들어 처리

2023-07-11 01:53 UTC, merged